theme: jekyll-theme-midnight
title: Tinkerer
description: "Code and Climate Change. Blog about software development in ClimateTech"
show_downloads: false
url: https://www.gustavwengel.dk
repository: "GeeWee/geewee.github.io"
author: Gustav Wengel
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
plugins:
  - jekyll-feed
kramdown:
  hard_wrap: true
